import os

# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages
# im trying to call you dan check ur messages


# no. this is bad
os.system("""

pip install websockets


""")